MAIN_BUTTON_ID = 'auto_mortise_script_main_button'
BODIES_SELECT = 'auto_mortise_script_small_face_select'
TAB_MAX_SIZE = 'auto_mortise_script_tab_max_size'
TAB_TIMELINE_GROUP = 'tabs'
TAB_SKETCH_PREFIX = 'tab - '
